language: dart
dart: stable
script:
  - cd built_json_generator
  - pub get
  - pub run test
  - cd ../example
  - pub get
  - dart tool/build.dart
  - pub run test
  - cd ../chat_example
  - pub get
  - dart tool/build.dart
  - pub run test
